---
- name: Variables FACT
  hosts: servidores_de_aplicaciones
  
  tasks:
    - name: Ver la memoria de la maquina
      ansible.builtin.debug:
        msg: "La memoria es {{ansible_facts['memfree_mb']}}"

    - name: Ver el gateway la maquina
      ansible.builtin.debug:
        msg: "El gateway de la maquina es {{ansible_facts.default_ipv4.gateway}}"

    - name: Ver los dos primeros procesadores
      ansible.builtin.debug: 
        msg: "Los dos primeros procesadores son {{ansible_facts['processor'][0:2]}}"

    - name: Ver toda la informacion de la memoria
      ansible.builtin.debug:
        msg: "La informacion al completo de la memoria es {{ansible_facts.memory_mb}}"